- title: true
- shields:
    style: 'flat-square'
    shields:
      - alt: 'flipactual'
        image: 'badge/😋-flipactual-43A6F6.svg'
        link: 'https://flipactual.com/'
      - alt: 'Travis'
        image: 'travis/flipactual/www.havefeelings.today.svg'
        link: 'https://travis-ci.org/flipactual/www.havefeelings.today/'
- license: true
